spring:
  application:
    name: Yummier
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/compose-postgres}
    username: ${SPRING_DATASOURCE_USERNAME:compose-postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:compose-postgres}

springdoc:
  api-docs:
    path: /api-docs